### ISSUE TITLE
Climber Subsystem

### ISSUE THREAD

**Issue by PepperLola** [Pigmice2733/frc-2022#4]
Initial implementation should include 4 motors. Two will be for the lifting set of arms, and two will be for the rotating arms. The two motors in a pair should spin in opposite directions (`motor.setInverted(true)` on the motors on one side). One motor in each pair should be the leader and the other should be the follower (the follower will copy whichever instructions get sent to the leader) by calling `follower.follow(leader)`.

Climb commands will be necessary later, but we don't have to worry about that now, or until we have the robot built.

**Comment by ev118** [comment]
At this point I believe that the climber subsystem is complete to the extent that it can be without testing; I will leave the branch open so necessary changes can be made in the future, but I highly advise against making any changes to this branch until we have a prototype to test on.
